import {readFile,mkdir,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,root),'utf8');
const [html,css,math,swing,app]=await Promise.all(['src/index.html','src/style.css','src/orientation.mjs','src/swing.mjs','src/app.mjs'].map(read));
const script=[math,swing,app].map(src=>src.replace(/^import[^\n]*\n/gm,'').replace(/^export /gm,'')).join('\n');
const output=html.replace('/* STYLES */',()=>css).replace('/* SCRIPT */',()=>script);
await mkdir(new URL('docs/',root),{recursive:true});
await writeFile(new URL('docs/index.html',root),output);
await writeFile(new URL('docs/.nojekyll',root),'');
console.log(`Built docs/index.html (${Buffer.byteLength(output)} bytes), no external dependencies.`);
